service: lets-recycle
frameworkVersion: '2'

provider:
  name: aws
  runtime: dotnetcore3.1
  lambdaHashingVersion: 20201221
  region: eu-west-2
  profile: serverless
  environment:
    RDS_ENDPOINT: ${self:custom.awsSecret.endpoint}
    RDS_PORT: ${self:custom.awsSecret.port}
    RDS_DATABASE: ${self:custom.awsSecret.database}
    RDS_USER: ${self:custom.awsSecret.user}
    RDS_PASSWORD: ${self:custom.awsSecret.password}

package:
  individually: true

custom:
  awsSecret: ${ssm:/aws/reference/secretsmanager/dev-mysql~true}

functions:
 
  apiGet:
    handler: LambdaAssembly::LambdaApi.LambdaApi::ApiGet
    package:
      artifact: bin/Release/netcoreapp3.1/package.zip
    events:
      - httpApi:
          path: /{api+}
          method: get
  apiPost:
    handler: LambdaAssembly::LambdaApi.LambdaApi::ApiPost
    package:
      artifact: bin/Release/netcoreapp3.1/package.zip
    events:
      - httpApi:
          path: /{api+}
          method: post
      
   